Added checks to allow drs replicates to fail in slave provisioning.  They do not appear to work in Dockerhub automated builds.

diff --git a/bin/samba-provisioning b/bin/samba-provisioning
--- a/bin/samba-provisioning
+++ b/bin/samba-provisioning
@@ -272,9 +272,17 @@ post_provisioning() {
     mast="$(host $MASTER_IP $MASTER_IP | grep "name pointer" | sed 's/^.*pointer //' | cut -d '.' -f 1)"
     if [ -n "$part" -a -n "$mast" ]; then
       echo "samba-tool drs replicate $HOST_NAME $mast $part"
-      samba-tool drs replicate $HOST_NAME $mast $part
+      if ! samba-tool drs replicate $HOST_NAME $mast $part ; then
+        echo "Replication failed, continuing anyway"
+      else
+        echo "Replication suceeded!"
+      fi
       echo "samba-tool drs replicate $mast $HOST_NAME $part"
-      samba-tool drs replicate $mast $HOST_NAME $part
+      if ! samba-tool drs replicate $mast $HOST_NAME $part ; then
+        echo "Replication failed, continuing anyway"
+      else
+        echo "Replication suceeded!"
+      fi
     fi
 
     # If slave show replication status
