Added some test retries to samba-tests.

diff --git a/bin/samba-tests b/bin/samba-tests
--- a/bin/samba-tests
+++ b/bin/samba-tests
@@ -49,7 +49,7 @@ nsupdate_add() {
 	UPDATE
 
   # Verify the record was added.
-  test="Lookup of record type $type ${key}"
+  test="Lookup $type record for ${key}"
   if ! host -t $type $key ; then
     result=$?
     log_fail_optional "$test"
@@ -74,7 +74,7 @@ nsupdate_del() {
 	UPDATE
 
   # Verify that the record was deleted.
-  test="Delete of record type $type for $key"
+  test="Delete $type record for $key"
   if host -t $type $key 2>&1 >/dev/null ; then
     result=$?
     log_fail_optional "$test"
@@ -137,7 +137,7 @@ test_nsupdate() {
 
 dns_lookup_test() {
 
-  test="Lookup of record type $1 $2"
+  test="Lookup $1 record for $2"
   if ! host -t $1 $2 ; then
     log_fail "$test"
   else
@@ -153,22 +153,37 @@ test_samba() {
 
   # Verifying the File Server
 
-  # Only run this test if smbclient is available.
+  # Only run these tests if smbclient is available.
   if [ -n "$(command -v smbclient 2> /dev/null)" ]; then
+    # List shares test, retry if necessary.
     test="smbclient -L $HOST_IP -U%"
-    if ! smbclient -L $HOST_IP -U% ; then
-      log_fail "$test"
-    else
-      log_pass "$test"
-    fi
+    for try in $(seq -s ' ' 1 3) ; do
+      smbclient -L $HOST_IP -U%
+      rc="$?"
+      if [ "$rc" != "0" ]; then
+        echo "Retrying list shares test ($try)."
+        sleep 10s
+      else
+        log_pass "$test"
+        break
+      fi
+    done
+    [ "$rc" != "0" ] && log_fail "$test"
+    # Login test, retry if necessary.
     test="smbclient //${HOST_NAME}.${DOMAIN}/netlogon -U administrator -k -c 'ls'"
-    echo "$PASSWORD" | kinit Administrator
-    smbclient //${HOST_NAME}.${DOMAIN}/netlogon -U administrator -k -c 'ls' 2>&1
-    if [ "$?" != "0" ]; then
-      log_fail "$test"
-    else
-      log_pass "$test"
-    fi
+    for try in $(seq -s ' ' 1 3) ; do
+      echo "$PASSWORD" | kinit Administrator
+      smbclient //${HOST_NAME}.${DOMAIN}/netlogon -U administrator -k -c 'ls' 2>&1
+      rc="$?"
+      if [ "$rc" != "0" ]; then
+        echo "Retrying login test ($try)."
+        sleep 10s
+      else
+        log_pass "$test"
+        break
+      fi
+    done
+    [ "$rc" != "0" ] && log_fail "$test"
   fi
 
   # Verifying DNS
