Added tests for dynamic dns updates.

diff --git a/bin/samba-provision b/bin/samba-provision
--- a/bin/samba-provision
+++ b/bin/samba-provision
@@ -70,6 +70,7 @@ post_provisioning() {
 		[ "${subnet}" = "8" ]  && node="$(echo "${HOST_IP}" | awk -F '.' '{print $4 "." $3 "." $2}')"
 		if ! host -t SOA "${revzone}.in-addr.arpa" 2>/dev/null | grep -q 'has SOA' ; then
 			echo "Info: Adding reverse dns zone ${revzone}.in-addr.arpa."
+			echo samba-tool dns zonecreate "${HOST}.${domain}" "${revzone}.in-addr.arpa" -P
 			samba-tool dns zonecreate "${HOST}.${domain}" "${revzone}.in-addr.arpa" -P 2>&1
 		else
 			echo "Info: Reverse zone ${revzone}.in-addr.arpa exists."
@@ -116,6 +117,21 @@ post_provisioning() {
 		# Set the the dhcp users password to never expire and add it to the DnsAdmins group.
 		samba-tool user setexpiry dhcpduser --noexpiry
 		samba-tool group addmembers DnsAdmins dhcpduser
+	fi
+
+	echo samba-tool domain exportkeytab --principal="dhcpduser@${realm}" "${private_dir}/dhcpduser.keytab"
+	if samba-tool domain exportkeytab --principal="dhcpduser@${realm}" "${private_dir}/dhcpduser.keytab" ; then
+		# Note: If there is no dhcpduser defined, no error is returned and no keytab file is created.
+		if [ -e "${private_dir}/dhcpduser.keytab" ]; then
+			# Change permissions on the dhcpduser keytab.
+			chmod 400 "${private_dir}/dhcpduser.keytab"
+			# Copy this to /etc where the dhcp-dyndns.sh script expects it.
+			cp -a "${private_dir}/dhcpduser.keytab" /etc/dhcpduser.keytab
+		else
+			echo "Warning: exportkeytab for dhcpduser failed, continuing anyway!"
+		fi
+	else
+		echo "Warning: exportkeytab for dhcpduser failed, continuing anyway!"
 	fi
 }
 
@@ -298,7 +314,7 @@ echo "Info: Copying the kerberos configuration generated by Samba."
 [ -e /etc/krb5.conf ] && mv /etc/krb5.conf /etc/krb5.conf.orig
 cp -f "${private_dir}/krb5.conf" /etc/
 
-echo "Info: Setting dns to self and dns search to this domain."
+echo "Info: Setting dns to self (${HOST_IP}) and dns search to this domain (${domain})."
 if command -v nmcli >/dev/null 2>&1 ; then
 	echo "Info: Updating nameserver with nmcli."
 	conn="$(nmcli -t -f NAME c show --active | grep -v '^lo' | head -1)"
@@ -365,6 +381,16 @@ fi
 
 # If this is a test run, set the status to running and wait for the shutdown signal.
 if [ -d /sut ]; then
+	# Add authorized key for testing dynamic dns updates.
+	mkdir -p /root/.ssh
+	echo 'command="/usr/local/bin/samba-dyndns-wrapper" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2BkIqATjbZHBQbUGwDdqXI3JaAk/ZcON7bkp2XQrRn dns-updates' >>/root/.ssh/authorized_keys
+	if ! systemctl is-active systemd-journald >/dev/null 2>&1 ; then
+		[ -e /usr/libexec/openssh/sshd-keygen ] && /usr/libexec/openssh/sshd-keygen ed25519
+		mkdir -p /run/sshd
+		/usr/sbin/sshd || echo "Warning: Error starting SSH daemon."
+	else
+		systemctl start sshd || echo "Warning: Error starting SSH daemon."
+	fi
 	echo >"/sut/${HOST}.running"
 	wait_for_file "/sut/${HOST}.shutdown"
 	systemctl is-active systemd-journald >/dev/null 2>&1 && kill -s "RTMIN+3" 1
diff --git a/bin/samba-tests-sut b/bin/samba-tests-sut
--- a/bin/samba-tests-sut
+++ b/bin/samba-tests-sut
@@ -10,6 +10,21 @@ wait_for_file() {
 	done
 }
 
+lookup_test() {
+
+	test="Lookup $1 record for $2"
+	[ "$3" = "fail" ] && test="Delete of $1 record for $2"
+	if host -t "$1" "$2" >/dev/null 2>&1 ; then
+		[ "$3" = "pass" ] && log_pass "$test"
+		[ "$3" = "fail" ] && log_fail "$test"
+		rc="0"
+	else
+		[ "$3" = "pass" ] && log_fail "$test"
+		[ "$3" = "fail" ] && log_pass "$test"
+		rc="1"
+	fi
+}
+
 run_tests() {
 
   HOST_NAME="$1"
@@ -24,6 +39,42 @@ run_tests() {
 	__EOF__
 
   test_samba
+
+  mkdir -p ~/.ssh
+  cat >~/.ssh/id_ed25519 <<-__EOD__
+	-----BEGIN OPENSSH PRIVATE KEY-----
+	b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
+	QyNTUxOQAAACAtgZCKgE422RwUG1BsA3alyNyWgJP2XDje25Kdl0K0ZwAAAJiZ2Ktdmdir
+	XQAAAAtzc2gtZWQyNTUxOQAAACAtgZCKgE422RwUG1BsA3alyNyWgJP2XDje25Kdl0K0Zw
+	AAAEBHe9Ja34lhnan1fbEoYuPqZ8qpx9iY3t85dFVzKmNrvi2BkIqATjbZHBQbUGwDdqXI
+	3JaAk/ZcON7bkp2XQrRnAAAAE2R5bmFtaWNAZG5zLnVwZGF0ZXMBAg==
+	-----END OPENSSH PRIVATE KEY-----
+	__EOD__
+  chmod 400 ~/.ssh/id_ed25519
+
+  # Generate a dummy address in this network segment to add to dns.
+  ip="$(echo "${HOST_IP}" | cut -d. -f1-3).250"
+  ptr="$(echo "${ip}" | awk -F '.' '{print $4 "." $3 "." $2 "." $1 ".in-addr.arpa"}')"
+
+  # Test the dhcp-dyndns.sh add functionality.
+  echo ssh -o StrictHostKeyChecking=no root@"${HOST_IP}" samba-dyndns-wrapper "add" "$ip" "nil" "nstest"
+  ssh -o StrictHostKeyChecking=no root@"${HOST_IP}" samba-dyndns-wrapper "add" "$ip" "nil" "nstest" || rc="$?"
+  [ "${rc:-0}" != "0" ] && echo "ssh rc is $rc"
+  lookup_test A   "$ip"   pass
+  test_a="$rc"
+  lookup_test PTR "$ptr"  pass
+  test_ptr="$rc"
+
+  # Test the dhcp-dyndns.sh delete functionality.
+  echo ssh -o StrictHostKeyChecking=no root@"${HOST_IP}" samba-dyndns-wrapper "delete" "$ip" "nil"
+  ssh -o StrictHostKeyChecking=no root@"${HOST_IP}" samba-dyndns-wrapper "delete" "$ip" "nil" || rc="$?"
+  [ "${rc:-0}" != "0" ] && echo "ssh rc is $rc"
+  if [ "$test_a"   = "0" ]; then
+	lookup_test A   "$ip"   fail
+  fi
+  if [ "$test_ptr" = "0" ]; then
+	lookup_test PTR "$ptr"  fail
+  fi
 }
 
 echo "Starting system unit tests!"
